{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.secretName" . }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ required "auth.rootUser is required" .Values.auth.rootUser | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ required "auth.rootPassword is required" .Values.auth.rootPassword | quote }}
  {{- if .Values.auth.database }}
  MONGO_INITDB_DATABASE: {{ .Values.auth.database | quote }}
  {{- end }}
{{- end }}