{{- if .Values.kafkaUi.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kafka.fullname" . }}-ui
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  replicas: {{ .Values.kafkaUi.replicas }}
  selector:
    matchLabels:
      {{- include "kafka.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ui
  template:
    metadata:
      labels:
        {{- include "kafka.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ui
        {{- with .Values.kafkaUi.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.kafkaUi.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      automountServiceAccountToken: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kafkaUi.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      containers:
        - name: kafka-ui
          image: "{{ .Values.image.kafkaUi.repository }}:{{ .Values.image.kafkaUi.tag }}"
          imagePullPolicy: {{ .Values.image.kafkaUi.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.kafkaUi.service.port }}
              protocol: TCP
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: {{ .Release.Name }}
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: "{{ include "kafka.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.service.externalPort }}"
            - name: DYNAMIC_CONFIG_ENABLED
              value: "true"
            {{- with .Values.kafkaUi.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.kafkaUi.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.kafkaUi.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kafkaUi.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kafkaUi.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}