apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kafka.fullname" . }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  minAvailable: {{ sub (int .Values.replicas) 1 }}
  selector:
    matchLabels:
      {{- include "kafka.selectorLabels" . | nindent 6 }}