{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.secretName" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ required "auth.rootPassword is required" .Values.auth.rootPassword | toString | b64enc | quote }}
  {{- if .Values.auth.database }}
  MYSQL_DATABASE: {{ .Values.auth.database | toString | b64enc | quote }}
  {{- end }}
  {{- if and .Values.auth.user .Values.auth.password }}
  MYSQL_USER: {{ .Values.auth.user | toString | b64enc | quote }}
  MYSQL_PASSWORD: {{ .Values.auth.password | toString | b64enc | quote }}
  {{- end }}
  {{- if .Values.cluster.enabled }}
  MYSQL_REPLICATION_USER: {{ .Values.auth.replicationUser | toString | b64enc | quote }}
  MYSQL_REPLICATION_PASSWORD: {{ .Values.auth.replicationPassword | toString | b64enc | quote }}
  {{- end }}
{{- end }}