{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis.secretName" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
type: Opaque
stringData:
  redis-password: {{ required "auth.password is required when auth.enabled is true" .Values.auth.password | quote }}
{{- end }}
