apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: redis
      port: {{ .Values.service.port }}
      targetPort: redis
      protocol: TCP
    {{- if .Values.cluster.enabled }}
    - name: cluster-bus
      port: {{ .Values.cluster.busPort }}
      targetPort: cluster-bus
      protocol: TCP
    {{- end }}
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.headlessServiceName" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
  {{- with .Values.service.headlessAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: redis
      port: {{ .Values.service.port }}
      targetPort: redis
      protocol: TCP
    {{- if .Values.cluster.enabled }}
    - name: cluster-bus
      port: {{ .Values.cluster.busPort }}
      targetPort: cluster-bus
      protocol: TCP
    {{- end }}
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}
