{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opensearch.secretName" . }}
  labels:
    {{- include "opensearch.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.secretKeys.adminPassword }}: {{ .Values.auth.adminPassword | quote }}
{{- end }}
