{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.secretName" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_USER: {{ required "auth.postgresUser is required" .Values.auth.postgresUser | toString | b64enc | quote }}
  POSTGRES_PASSWORD: {{ required "auth.postgresPassword is required" .Values.auth.postgresPassword | toString | b64enc | quote }}
  POSTGRES_DB: {{ required "auth.postgresDatabase is required" .Values.auth.postgresDatabase | toString | b64enc | quote }}
  POSTGRES_REPLICATION_USER: {{ .Values.auth.replicationUser | toString | b64enc | quote }}
  POSTGRES_REPLICATION_PASSWORD: {{ .Values.auth.replicationPassword | toString | b64enc | quote }}
{{- end }}
