apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: postgres
      port: {{ .Values.service.port }}
      targetPort: postgres
      protocol: TCP
  selector:
    {{- if .Values.cluster.enabled }}
    {{- include "postgres.primarySelectorLabels" . | nindent 4 }}
    {{- else }}
    {{- include "postgres.selectorLabels" . | nindent 4 }}
    {{- end }}
{{- if and .Values.cluster.enabled .Values.readOnlyService.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.readOnlyServiceName" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
    app.kubernetes.io/component: replica
  {{- with .Values.readOnlyService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.readOnlyService.type }}
  ports:
    - name: postgres
      port: {{ .Values.readOnlyService.port }}
      targetPort: postgres
      protocol: TCP
  selector:
    {{- include "postgres.replicaSelectorLabels" . | nindent 4 }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.headlessServiceName" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
  {{- with .Values.headlessService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: postgres
      port: {{ .Values.service.port }}
      targetPort: postgres
      protocol: TCP
  selector:
    {{- include "postgres.selectorLabels" . | nindent 4 }}
