{{- if and .Values.web.enabled .Values.podDisruptionBudget.web.enabled (gt (int .Values.web.replicas) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "langfuse.fullname" . }}-web
  labels:
    {{- include "langfuse.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.web.minAvailable }}
  selector:
    matchLabels:
      {{- include "langfuse.webSelectorLabels" . | nindent 6 }}
{{- end }}
{{- if and .Values.worker.enabled .Values.podDisruptionBudget.worker.enabled (gt (int .Values.worker.replicas) 1) }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "langfuse.fullname" . }}-worker
  labels:
    {{- include "langfuse.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.worker.minAvailable }}
  selector:
    matchLabels:
      {{- include "langfuse.workerSelectorLabels" . | nindent 6 }}
{{- end }}
