{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rabbitmq.secretName" . }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: {{ required "auth.defaultUser is required" .Values.auth.defaultUser | quote }}
  RABBITMQ_DEFAULT_PASS: {{ required "auth.defaultPass is required" .Values.auth.defaultPass | quote }}
  RABBITMQ_ERLANG_COOKIE: {{ include "rabbitmq.erlangCookie" . | quote }}
{{- end }}