{{- if .Values.relay.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sentry.fullname" . }}-relay
  labels:
    {{- include "sentry.labels" . | nindent 4 }}
data:
  config.yml: |
    log_level: debug
    relay:
      mode: managed
      upstream: "http://{{ include "sentry.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.service.port }}"
      host: 0.0.0.0
      port: {{ .Values.relay.port }}
    processing:
      enabled: true
      kafka_config:
        - name: bootstrap.servers
          value: "{{ .Values.kafka.bootstrapServers }}"
        - name: message.max.bytes
          value: {{ .Values.relay.kafkaMessageMaxBytes | int64 | quote }}
      redis: "redis://{{ .Values.redis.host }}:{{ .Values.redis.port }}/0"
    cache:
      project_expiry: {{ .Values.relay.projectExpiry }}
      project_grace_period: {{ .Values.relay.projectGracePeriod }}
      miss_expiry: {{ .Values.relay.missExpiry }}
    {{- if and .Values.relay.redis .Values.relay.redis.enabled }}
    redis:
      host: "{{ .Values.relay.redis.host }}"
      port: {{ .Values.relay.redis.port }}
    {{- end }}
{{- end }}
