{{- if not .Values.auth.existingSecret }}
{{- $secretName := include "sentry.secretName" . }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "sentry.labels" . | nindent 4 }}
type: Opaque
{{- if $existing }}
data:
  SENTRY_SECRET_KEY: {{ index $existing.data "SENTRY_SECRET_KEY" }}
{{- else }}
stringData:
  SENTRY_SECRET_KEY: {{ .Values.auth.secretKey | default (randAlphaNum 64) | quote }}
{{- end }}
{{- end }}