{{- if .Values.snuba.consumer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sentry.fullname" . }}-snuba-consumer
  labels:
    {{- include "sentry.snubaConsumerSelectorLabels" . | nindent 4 }}
    {{- include "sentry.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.snuba.consumer.replicas }}
  selector:
    matchLabels:
      {{- include "sentry.snubaConsumerSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sentry.snubaConsumerSelectorLabels" . | nindent 8 }}
        {{- with .Values.snuba.consumer.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.snuba.consumer.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "sentry.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.snuba.consumer.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.snuba.consumer.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      {{- if and .Values.kafka.autoCreateTopics .Values.kafka.bootstrapServers }}
      initContainers:
        {{- include "sentry.kafkaTopicInitContainer" . | nindent 8 }}
      {{- end }}
      containers:
        - name: snuba-consumer
          image: {{ include "sentry.snubaImage" . }}
          imagePullPolicy: {{ .Values.image.snuba.pullPolicy }}
          {{- with .Values.snuba.consumer.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command: ["snuba", "consumer", "--storage", "errors", "--auto-offset-reset", "earliest"]
          env:
            - name: SNUBA_SETTINGS
              value: /etc/snuba/settings.py
            - name: CLICKHOUSE_HOST
              value: {{ .Values.clickhouse.host | quote }}
            - name: CLICKHOUSE_HTTP_PORT
              value: {{ .Values.clickhouse.httpPort | quote }}
            - name: CLICKHOUSE_PORT
              value: {{ .Values.clickhouse.tcpPort | quote }}
            - name: CLICKHOUSE_DB
              value: {{ .Values.clickhouse.database | quote }}
            - name: CLICKHOUSE_DATABASE
              value: {{ .Values.clickhouse.database | quote }}
            - name: CLICKHOUSE_USER
              value: {{ .Values.clickhouse.user | quote }}
            - name: CLICKHOUSE_PASSWORD
              {{- include "sentry.clickhousePasswordEnvValue" . | nindent 14 }}
            - name: REDIS_HOST
              value: {{ .Values.redis.host | quote }}
            - name: REDIS_PORT
              value: {{ .Values.redis.port | quote }}
            - name: REDIS_PASSWORD
              {{- include "sentry.redisPasswordEnvValue" . | nindent 14 }}
            - name: DEFAULT_BROKERS
              value: "{{ .Values.kafka.bootstrapServers }}"
            {{- with .Values.snuba.consumer.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: snuba-conf
              mountPath: /etc/snuba
              readOnly: true
          {{- with .Values.snuba.consumer.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        - name: snuba-consumer-group-attributes
          image: {{ include "sentry.snubaImage" . }}
          imagePullPolicy: {{ .Values.image.snuba.pullPolicy }}
          {{- with .Values.snuba.consumer.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command: ["snuba", "consumer", "--storage", "group_attributes", "--auto-offset-reset", "earliest"]
          env:
            - name: SNUBA_SETTINGS
              value: /etc/snuba/settings.py
            - name: CLICKHOUSE_HOST
              value: {{ .Values.clickhouse.host | quote }}
            - name: CLICKHOUSE_HTTP_PORT
              value: {{ .Values.clickhouse.httpPort | quote }}
            - name: CLICKHOUSE_PORT
              value: {{ .Values.clickhouse.tcpPort | quote }}
            - name: CLICKHOUSE_DB
              value: {{ .Values.clickhouse.database | quote }}
            - name: CLICKHOUSE_DATABASE
              value: {{ .Values.clickhouse.database | quote }}
            - name: CLICKHOUSE_USER
              value: {{ .Values.clickhouse.user | quote }}
            - name: CLICKHOUSE_PASSWORD
              {{- include "sentry.clickhousePasswordEnvValue" . | nindent 14 }}
            - name: REDIS_HOST
              value: {{ .Values.redis.host | quote }}
            - name: REDIS_PORT
              value: {{ .Values.redis.port | quote }}
            - name: REDIS_PASSWORD
              {{- include "sentry.redisPasswordEnvValue" . | nindent 14 }}
            - name: DEFAULT_BROKERS
              value: "{{ .Values.kafka.bootstrapServers }}"
            {{- with .Values.snuba.consumer.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: snuba-conf
              mountPath: /etc/snuba
              readOnly: true
          {{- with .Values.snuba.consumer.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.snuba.consumer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.snuba.consumer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.snuba.consumer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: snuba-conf
          configMap:
            name: {{ include "sentry.fullname" . }}-snuba
{{- end }}
