{{- if .Values.taskbroker.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentry.fullname" . }}-taskbroker
  labels:
    {{- include "sentry.labels" . | nindent 4 }}
    app.kubernetes.io/component: taskbroker
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 50051
      targetPort: grpc
      protocol: TCP
  selector:
    {{- include "sentry.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: taskbroker
{{- end }}