{{- if .Values.web.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sentry.fullname" . }}-web
  labels:
    {{- include "sentry.webSelectorLabels" . | nindent 4 }}
    {{- include "sentry.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      {{- include "sentry.webSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sentry.webSelectorLabels" . | nindent 8 }}
        {{- with .Values.web.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.web.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "sentry.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      containers:
        - name: sentry-web
          image: {{ include "sentry.webImage" . }}
          imagePullPolicy: {{ .Values.image.sentry.pullPolicy }}
          {{- with .Values.web.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command: ["sentry", "run", "web"]
          ports:
            - name: http
              containerPort: {{ .Values.web.port }}
              protocol: TCP
          env:
            - name: SENTRY_WEB_HOST
              value: "0.0.0.0"
            - name: SENTRY_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "sentry.secretName" . }}
                  key: SENTRY_SECRET_KEY
            - name: SENTRY_DB_NAME
              value: {{ .Values.postgres.database | quote }}
            - name: SENTRY_DB_USER
              value: {{ .Values.postgres.user | quote }}
            - name: SENTRY_DB_PASSWORD
              {{- include "sentry.postgresPasswordEnvValue" . | nindent 14 }}
            - name: SENTRY_POSTGRES_HOST
              value: {{ .Values.postgres.host | quote }}
            - name: SENTRY_POSTGRES_PORT
              value: {{ .Values.postgres.port | quote }}
            - name: SENTRY_REDIS_HOST
              value: {{ .Values.redis.host | quote }}
            - name: SENTRY_REDIS_PORT
              value: {{ .Values.redis.port | quote }}
            - name: SENTRY_REDIS_PASSWORD
              {{- include "sentry.redisPasswordEnvValue" . | nindent 14 }}
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Values.kafka.bootstrapServers | quote }}
            {{- if .Values.snuba.api.enabled }}
            - name: SNUBA_HOST
              value: "http://{{ include "sentry.fullname" . }}-snuba-api.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.snuba.api.port }}"
            {{- end }}
            {{- if .Values.relay.enabled }}
            - name: SENTRY_RELAY_HOST
              value: {{ include "sentry.fullname" . }}-relay
            - name: SENTRY_RELAY_PORT
              value: {{ .Values.relay.port | quote }}
            {{- end }}
            - name: SENTRY_SYSTEM_URL
              value: {{ .Values.system.url | quote }}
            - name: SENTRY_ADMIN_EMAIL
              value: {{ .Values.system.adminEmail | quote }}
            {{- if .Values.filestore.backend }}
            - name: SENTRY_FILESTORE
              value: {{ .Values.filestore.backend | quote }}
            {{- end }}
            {{- if eq .Values.filestore.backend "filesystem" }}
            - name: SENTRY_FILESTORE_DIR
              value: {{ .Values.filestore.filesystem.path | quote }}
            {{- end }}
            {{- include "sentry.filestoreS3Env" . | nindent 12 }}
            - name: SENTRY_WEB_WORKERS
              value: {{ .Values.web.workers | quote }}
            - name: SENTRY_WEB_THREADS
              value: {{ .Values.web.threads | quote }}
            - name: SENTRY_WEB_HTTP_KEEPALIVE
              value: {{ .Values.web.httpKeepalive | quote }}
            - name: SENTRY_WEB_HARAKIRI
              value: {{ .Values.web.harakiri | quote }}
            - name: SENTRY_WEB_MAX_REQUESTS
              value: {{ .Values.web.maxRequests | int64 | quote }}
            - name: SENTRY_WEB_MAX_REQUESTS_DELTA
              value: {{ .Values.web.maxRequestsDelta | int64 | quote }}
            - name: SENTRY_WEB_MAX_WORKER_LIFETIME
              value: {{ .Values.web.maxWorkerLifetime | int64 | quote }}
            - name: SENTRY_WEB_BUFFER_SIZE
              value: {{ .Values.web.bufferSize | int64 | quote }}
            - name: SENTRY_WEB_LIMIT_POST
              value: {{ .Values.web.limitPost | int64 | quote }}
            - name: SENTRY_WEB_RELOAD_ON_RSS
              value: {{ .Values.web.reloadOnRss | int64 | quote }}
            {{- with .Values.web.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: sentry-conf
              mountPath: /etc/sentry
              readOnly: true
            {{- if eq .Values.filestore.backend "filesystem" }}
            {{- if .Values.filestore.filesystem.persistence.enabled }}
            - name: filestore
              mountPath: {{ .Values.filestore.filesystem.path }}
            {{- end }}
            {{- end }}
          {{- with .Values.web.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.web.startupProbe.enabled }}
          startupProbe:
            httpGet:
              path: {{ .Values.web.startupProbe.path | quote }}
              port: http
            initialDelaySeconds: {{ .Values.web.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.web.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.web.startupProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.web.startupProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.web.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.web.readinessProbe.path | quote }}
              port: http
            initialDelaySeconds: {{ .Values.web.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.web.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.web.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.web.readinessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.web.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.web.livenessProbe.path | quote }}
              port: http
            initialDelaySeconds: {{ .Values.web.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.web.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.web.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.web.livenessProbe.failureThreshold }}
          {{- end }}
      volumes:
        - name: sentry-conf
          configMap:
            name: {{ include "sentry.fullname" . }}-sentry
        {{- if eq .Values.filestore.backend "filesystem" }}
        {{- if .Values.filestore.filesystem.persistence.enabled }}
        - name: filestore
          persistentVolumeClaim:
            {{- if .Values.filestore.filesystem.persistence.existingClaim }}
            claimName: {{ .Values.filestore.filesystem.persistence.existingClaim }}
            {{- else }}
            claimName: {{ include "sentry.fullname" . }}-data
            {{- end }}
        {{- end }}
        {{- end }}
      {{- with .Values.web.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
